const JSONData = [
  {
    rowId: 1,
    orderId: "CA-2016-152156",
    orderDate: "11/8/16",
    shipDate: "11/11/16",
    shipMode: "Second Class",
    customerId: "CG-12520",
    customerName: "Claire Gute",
    segment: "Consumer",
    country: "United States",
    city: "Henderson",
    state: "Kentucky",
    postalCode: 42420,
    region: "South",
    productId: "FUR-BO-10001798",
    category: "Furniture",
    subCategory: "Bookcases",
    productName: "Bush Somerset Collection Bookcase",
    sales: 261.96,
    quantity: 2,
    discount: 0,
    profit: 41.9136,
  },
  {
    rowId: 2,
    orderId: "CA-2016-152156",
    orderDate: "11/8/16",
    shipDate: "11/11/16",
    shipMode: "Second Class",
    customerId: "CG-12520",
    customerName: "Claire Gute",
    segment: "Consumer",
    country: "United States",
    city: "Henderson",
    state: "Kentucky",
    postalCode: 42420,
    region: "South",
    productId: "FUR-CH-10000454",
    category: "Furniture",
    subCategory: "Chairs",
    productName: "Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back",
    sales: 731.94,
    quantity: 3,
    discount: 0,
    profit: 219.582,
  },
  {
    rowId: 3,
    orderId: "CA-2016-138688",
    orderDate: "6/12/16",
    shipDate: "6/16/16",
    shipMode: "Second Class",
    customerId: "DV-13045",
    customerName: "Darrin Van Huff",
    segment: "Corporate",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90036,
    region: "West",
    productId: "OFF-LA-10000240",
    category: "Office Supplies",
    subCategory: "Labels",
    productName: "Self-Adhesive Address Labels for Typewriters by Universal",
    sales: 14.62,
    quantity: 2,
    discount: 0,
    profit: 6.8714,
  },
  {
    rowId: 4,
    orderId: "US-2015-108966",
    orderDate: "10/11/15",
    shipDate: "10/18/15",
    shipMode: "Standard Class",
    customerId: "SO-20335",
    customerName: "Sean O'Donnell",
    segment: "Consumer",
    country: "United States",
    city: "Fort Lauderdale",
    state: "Florida",
    postalCode: 33311,
    region: "South",
    productId: "FUR-TA-10000577",
    category: "Furniture",
    subCategory: "Tables",
    productName: "Bretford CR4500 Series Slim Rectangular Table",
    sales: 957.5775,
    quantity: 5,
    discount: 0.45,
    profit: -383.031,
  },
  {
    rowId: 5,
    orderId: "US-2015-108966",
    orderDate: "10/11/15",
    shipDate: "10/18/15",
    shipMode: "Standard Class",
    customerId: "SO-20335",
    customerName: "Sean O'Donnell",
    segment: "Consumer",
    country: "United States",
    city: "Fort Lauderdale",
    state: "Florida",
    postalCode: 33311,
    region: "South",
    productId: "OFF-ST-10000760",
    category: "Office Supplies",
    subCategory: "Storage",
    productName: "Eldon Fold 'N Roll Cart System",
    sales: 22.368,
    quantity: 2,
    discount: 0.2,
    profit: 2.5164,
  },
  {
    rowId: 6,
    orderId: "CA-2014-115812",
    orderDate: "6/9/14",
    shipDate: "6/14/14",
    shipMode: "Standard Class",
    customerId: "BH-11710",
    customerName: "Brosina Hoffman",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90032,
    region: "West",
    productId: "FUR-FU-10001487",
    category: "Furniture",
    subCategory: "Furnishings",
    productName:
      "Eldon Expressions Wood and Plastic Desk Accessories, Cherry Wood",
    sales: 48.86,
    quantity: 7,
    discount: 0,
    profit: 14.1694,
  },
  {
    rowId: 7,
    orderId: "CA-2014-115812",
    orderDate: "6/9/14",
    shipDate: "6/14/14",
    shipMode: "Standard Class",
    customerId: "BH-11710",
    customerName: "Brosina Hoffman",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90032,
    region: "West",
    productId: "OFF-AR-10002833",
    category: "Office Supplies",
    subCategory: "Art",
    productName: "Newell 322",
    sales: 7.28,
    quantity: 4,
    discount: 0,
    profit: 1.9656,
  },
  {
    rowId: 8,
    orderId: "CA-2014-115812",
    orderDate: "6/9/14",
    shipDate: "6/14/14",
    shipMode: "Standard Class",
    customerId: "BH-11710",
    customerName: "Brosina Hoffman",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90032,
    region: "West",
    productId: "TEC-PH-10002275",
    category: "Technology",
    subCategory: "Phones",
    productName: "Mitel 5320 IP Phone VoIP phone",
    sales: 907.152,
    quantity: 6,
    discount: 0.2,
    profit: 90.7152,
  },
  {
    rowId: 9,
    orderId: "CA-2014-115812",
    orderDate: "6/9/14",
    shipDate: "6/14/14",
    shipMode: "Standard Class",
    customerId: "BH-11710",
    customerName: "Brosina Hoffman",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90032,
    region: "West",
    productId: "OFF-BI-10003910",
    category: "Office Supplies",
    subCategory: "Binders",
    productName: "DXL Angle-View Binders with Locking Rings by Samsill",
    sales: 18.504,
    quantity: 3,
    discount: 0.2,
    profit: 5.7825,
  },
  {
    rowId: 10,
    orderId: "CA-2014-115812",
    orderDate: "6/9/14",
    shipDate: "6/14/14",
    shipMode: "Standard Class",
    customerId: "BH-11710",
    customerName: "Brosina Hoffman",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90032,
    region: "West",
    productId: "OFF-AP-10002892",
    category: "Office Supplies",
    subCategory: "Appliances",
    productName: "Belkin F5C206VTEL 6 Outlet Surge",
    sales: 114.9,
    quantity: 5,
    discount: 0,
    profit: 34.47,
  },
  {
    rowId: 11,
    orderId: "CA-2014-115812",
    orderDate: "6/9/14",
    shipDate: "6/14/14",
    shipMode: "Standard Class",
    customerId: "BH-11710",
    customerName: "Brosina Hoffman",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90032,
    region: "West",
    productId: "FUR-TA-10001539",
    category: "Furniture",
    subCategory: "Tables",
    productName: "Chromcraft Rectangular Conference Tables",
    sales: 1706.184,
    quantity: 9,
    discount: 0.2,
    profit: 85.3092,
  },
  {
    rowId: 12,
    orderId: "CA-2014-115812",
    orderDate: "6/9/14",
    shipDate: "6/14/14",
    shipMode: "Standard Class",
    customerId: "BH-11710",
    customerName: "Brosina Hoffman",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90032,
    region: "West",
    productId: "TEC-PH-10002033",
    category: "Technology",
    subCategory: "Phones",
    productName: "Konftel 250 Conference phone - Charcoal black",
    sales: 911.424,
    quantity: 4,
    discount: 0.2,
    profit: 68.3568,
  },
  {
    rowId: 13,
    orderId: "CA-2017-114412",
    orderDate: "4/15/17",
    shipDate: "4/20/17",
    shipMode: "Standard Class",
    customerId: "AA-10480",
    customerName: "Andrew Allen",
    segment: "Consumer",
    country: "United States",
    city: "Concord",
    state: "North Carolina",
    postalCode: 28027,
    region: "South",
    productId: "OFF-PA-10002365",
    category: "Office Supplies",
    subCategory: "Paper",
    productName: "Xerox 1967",
    sales: 15.552,
    quantity: 3,
    discount: 0.2,
    profit: 5.4432,
  },
  {
    rowId: 14,
    orderId: "CA-2016-161389",
    orderDate: "12/5/16",
    shipDate: "12/10/16",
    shipMode: "Standard Class",
    customerId: "IM-15070",
    customerName: "Irene Maddox",
    segment: "Consumer",
    country: "United States",
    city: "Seattle",
    state: "Washington",
    postalCode: 98103,
    region: "West",
    productId: "OFF-BI-10003656",
    category: "Office Supplies",
    subCategory: "Binders",
    productName: "Fellowes PB200 Plastic Comb Binding Machine",
    sales: 407.976,
    quantity: 3,
    discount: 0.2,
    profit: 132.5922,
  },
  {
    rowId: 15,
    orderId: "US-2015-118983",
    orderDate: "11/22/15",
    shipDate: "11/26/15",
    shipMode: "Standard Class",
    customerId: "HP-14815",
    customerName: "Harold Pawlan",
    segment: "Home Office",
    country: "United States",
    city: "Fort Worth",
    state: "Texas",
    postalCode: 76106,
    region: "Central",
    productId: "OFF-AP-10002311",
    category: "Office Supplies",
    subCategory: "Appliances",
    productName:
      "Holmes Replacement Filter for HEPA Air Cleaner, Very Large Room, HEPA Filter",
    sales: 68.81,
    quantity: 5,
    discount: 0.8,
    profit: -123.858,
  },
  {
    rowId: 16,
    orderId: "US-2015-118983",
    orderDate: "11/22/15",
    shipDate: "11/26/15",
    shipMode: "Standard Class",
    customerId: "HP-14815",
    customerName: "Harold Pawlan",
    segment: "Home Office",
    country: "United States",
    city: "Fort Worth",
    state: "Texas",
    postalCode: 76106,
    region: "Central",
    productId: "OFF-BI-10000756",
    category: "Office Supplies",
    subCategory: "Binders",
    productName: "Storex DuraTech Recycled Plastic Frosted Binders",
    sales: 2.544,
    quantity: 3,
    discount: 0.8,
    profit: -3.816,
  },
  {
    rowId: 17,
    orderId: "CA-2014-105893",
    orderDate: "11/11/14",
    shipDate: "11/18/14",
    shipMode: "Standard Class",
    customerId: "PK-19075",
    customerName: "Pete Kriz",
    segment: "Consumer",
    country: "United States",
    city: "Madison",
    state: "Wisconsin",
    postalCode: 53711,
    region: "Central",
    productId: "OFF-ST-10004186",
    category: "Office Supplies",
    subCategory: "Storage",
    productName:
      'Stur-D-Stor Shelving, Vertical 5-Shelf: 72"H x 36"W x 18 1/2"D',
    sales: 665.88,
    quantity: 6,
    discount: 0,
    profit: 13.3176,
  },
  {
    rowId: 18,
    orderId: "CA-2014-167164",
    orderDate: "5/13/14",
    shipDate: "5/15/14",
    shipMode: "Second Class",
    customerId: "AG-10270",
    customerName: "Alejandro Grove",
    segment: "Consumer",
    country: "United States",
    city: "West Jordan",
    state: "Utah",
    postalCode: 84084,
    region: "West",
    productId: "OFF-ST-10000107",
    category: "Office Supplies",
    subCategory: "Storage",
    productName: "Fellowes Super Stor/Drawer",
    sales: 55.5,
    quantity: 2,
    discount: 0,
    profit: 9.99,
  },
  {
    rowId: 19,
    orderId: "CA-2014-143336",
    orderDate: "8/27/14",
    shipDate: "9/1/14",
    shipMode: "Second Class",
    customerId: "ZD-21925",
    customerName: "Zuschuss Donatelli",
    segment: "Consumer",
    country: "United States",
    city: "San Francisco",
    state: "California",
    postalCode: 94109,
    region: "West",
    productId: "OFF-AR-10003056",
    category: "Office Supplies",
    subCategory: "Art",
    productName: "Newell 341",
    sales: 8.56,
    quantity: 2,
    discount: 0,
    profit: 2.4824,
  },
  {
    rowId: 20,
    orderId: "CA-2014-143336",
    orderDate: "8/27/14",
    shipDate: "9/1/14",
    shipMode: "Second Class",
    customerId: "ZD-21925",
    customerName: "Zuschuss Donatelli",
    segment: "Consumer",
    country: "United States",
    city: "San Francisco",
    state: "California",
    postalCode: 94109,
    region: "West",
    productId: "TEC-PH-10001949",
    category: "Technology",
    subCategory: "Phones",
    productName: "Cisco SPA 501G IP Phone",
    sales: 213.48,
    quantity: 3,
    discount: 0.2,
    profit: 16.011,
  },
  {
    rowId: 21,
    orderId: "CA-2014-143336",
    orderDate: "8/27/14",
    shipDate: "9/1/14",
    shipMode: "Second Class",
    customerId: "ZD-21925",
    customerName: "Zuschuss Donatelli",
    segment: "Consumer",
    country: "United States",
    city: "San Francisco",
    state: "California",
    postalCode: 94109,
    region: "West",
    productId: "OFF-BI-10002215",
    category: "Office Supplies",
    subCategory: "Binders",
    productName: 'Wilson Jones Hanging View Binder, White, 1"',
    sales: 22.72,
    quantity: 4,
    discount: 0.2,
    profit: 7.384,
  },
  {
    rowId: 22,
    orderId: "CA-2016-137330",
    orderDate: "12/9/16",
    shipDate: "12/13/16",
    shipMode: "Standard Class",
    customerId: "KB-16585",
    customerName: "Ken Black",
    segment: "Corporate",
    country: "United States",
    city: "Fremont",
    state: "Nebraska",
    postalCode: 68025,
    region: "Central",
    productId: "OFF-AR-10000246",
    category: "Office Supplies",
    subCategory: "Art",
    productName: "Newell 318",
    sales: 19.46,
    quantity: 7,
    discount: 0,
    profit: 5.0596,
  },
  {
    rowId: 23,
    orderId: "CA-2016-137330",
    orderDate: "12/9/16",
    shipDate: "12/13/16",
    shipMode: "Standard Class",
    customerId: "KB-16585",
    customerName: "Ken Black",
    segment: "Corporate",
    country: "United States",
    city: "Fremont",
    state: "Nebraska",
    postalCode: 68025,
    region: "Central",
    productId: "OFF-AP-10001492",
    category: "Office Supplies",
    subCategory: "Appliances",
    productName: "Acco Six-Outlet Power Strip, 4' Cord Length",
    sales: 60.34,
    quantity: 7,
    discount: 0,
    profit: 15.6884,
  },
  {
    rowId: 24,
    orderId: "US-2017-156909",
    orderDate: "7/16/17",
    shipDate: "7/18/17",
    shipMode: "Second Class",
    customerId: "SF-20065",
    customerName: "Sandra Flanagan",
    segment: "Consumer",
    country: "United States",
    city: "Philadelphia",
    state: "Pennsylvania",
    postalCode: 19140,
    region: "East",
    productId: "FUR-CH-10002774",
    category: "Furniture",
    subCategory: "Chairs",
    productName: "Global Deluxe Stacking Chair, Gray",
    sales: 71.372,
    quantity: 2,
    discount: 0.3,
    profit: -1.0196,
  },
  {
    rowId: 25,
    orderId: "CA-2015-106320",
    orderDate: "9/25/15",
    shipDate: "9/30/15",
    shipMode: "Standard Class",
    customerId: "EB-13870",
    customerName: "Emily Burns",
    segment: "Consumer",
    country: "United States",
    city: "Orem",
    state: "Utah",
    postalCode: 84057,
    region: "West",
    productId: "FUR-TA-10000577",
    category: "Furniture",
    subCategory: "Tables",
    productName: "Bretford CR4500 Series Slim Rectangular Table",
    sales: 1044.63,
    quantity: 3,
    discount: 0,
    profit: 240.2649,
  },
  {
    rowId: 26,
    orderId: "CA-2016-121755",
    orderDate: "1/16/16",
    shipDate: "1/20/16",
    shipMode: "Second Class",
    customerId: "EH-13945",
    customerName: "Eric Hoffmann",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90049,
    region: "West",
    productId: "OFF-BI-10001634",
    category: "Office Supplies",
    subCategory: "Binders",
    productName: "Wilson Jones Active Use Binders",
    sales: 11.648,
    quantity: 2,
    discount: 0.2,
    profit: 4.2224,
  },
  {
    rowId: 27,
    orderId: "CA-2016-121755",
    orderDate: "1/16/16",
    shipDate: "1/20/16",
    shipMode: "Second Class",
    customerId: "EH-13945",
    customerName: "Eric Hoffmann",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90049,
    region: "West",
    productId: "TEC-AC-10003027",
    category: "Technology",
    subCategory: "Accessories",
    productName: "Imation 8GB Mini TravelDrive USB 2.0 Flash Drive",
    sales: 90.57,
    quantity: 3,
    discount: 0,
    profit: 11.7741,
  },
  {
    rowId: 28,
    orderId: "US-2015-150630",
    orderDate: "9/17/15",
    shipDate: "9/21/15",
    shipMode: "Standard Class",
    customerId: "TB-21520",
    customerName: "Tracy Blumstein",
    segment: "Consumer",
    country: "United States",
    city: "Philadelphia",
    state: "Pennsylvania",
    postalCode: 19140,
    region: "East",
    productId: "FUR-BO-10004834",
    category: "Furniture",
    subCategory: "Bookcases",
    productName:
      "Riverside Palais Royal Lawyers Bookcase, Royale Cherry Finish",
    sales: 3083.43,
    quantity: 7,
    discount: 0.5,
    profit: -1665.0522,
  },
  {
    rowId: 29,
    orderId: "US-2015-150630",
    orderDate: "9/17/15",
    shipDate: "9/21/15",
    shipMode: "Standard Class",
    customerId: "TB-21520",
    customerName: "Tracy Blumstein",
    segment: "Consumer",
    country: "United States",
    city: "Philadelphia",
    state: "Pennsylvania",
    postalCode: 19140,
    region: "East",
    productId: "OFF-BI-10000474",
    category: "Office Supplies",
    subCategory: "Binders",
    productName: "Avery Recycled Flexi-View Covers for Binding Systems",
    sales: 9.618,
    quantity: 2,
    discount: 0.7,
    profit: -7.0532,
  },
  {
    rowId: 30,
    orderId: "US-2015-150630",
    orderDate: "9/17/15",
    shipDate: "9/21/15",
    shipMode: "Standard Class",
    customerId: "TB-21520",
    customerName: "Tracy Blumstein",
    segment: "Consumer",
    country: "United States",
    city: "Philadelphia",
    state: "Pennsylvania",
    postalCode: 19140,
    region: "East",
    productId: "FUR-FU-10004848",
    category: "Furniture",
    subCategory: "Furnishings",
    productName:
      'Howard Miller 13-3/4" Diameter Brushed Chrome Round Wall Clock',
    sales: 124.2,
    quantity: 3,
    discount: 0.2,
    profit: 15.525,
  },
  {
    rowId: 31,
    orderId: "US-2015-150630",
    orderDate: "9/17/15",
    shipDate: "9/21/15",
    shipMode: "Standard Class",
    customerId: "TB-21520",
    customerName: "Tracy Blumstein",
    segment: "Consumer",
    country: "United States",
    city: "Philadelphia",
    state: "Pennsylvania",
    postalCode: 19140,
    region: "East",
    productId: "OFF-EN-10001509",
    category: "Office Supplies",
    subCategory: "Envelopes",
    productName: "Poly String Tie Envelopes",
    sales: 3.264,
    quantity: 2,
    discount: 0.2,
    profit: 1.1016,
  },
  {
    rowId: 32,
    orderId: "US-2015-150630",
    orderDate: "9/17/15",
    shipDate: "9/21/15",
    shipMode: "Standard Class",
    customerId: "TB-21520",
    customerName: "Tracy Blumstein",
    segment: "Consumer",
    country: "United States",
    city: "Philadelphia",
    state: "Pennsylvania",
    postalCode: 19140,
    region: "East",
    productId: "OFF-AR-10004042",
    category: "Office Supplies",
    subCategory: "Art",
    productName:
      "BOSTON Model 1800 Electric Pencil Sharpeners, Putty/Woodgrain",
    sales: 86.304,
    quantity: 6,
    discount: 0.2,
    profit: 9.7092,
  },
  {
    rowId: 33,
    orderId: "US-2015-150630",
    orderDate: "9/17/15",
    shipDate: "9/21/15",
    shipMode: "Standard Class",
    customerId: "TB-21520",
    customerName: "Tracy Blumstein",
    segment: "Consumer",
    country: "United States",
    city: "Philadelphia",
    state: "Pennsylvania",
    postalCode: 19140,
    region: "East",
    productId: "OFF-BI-10001525",
    category: "Office Supplies",
    subCategory: "Binders",
    productName:
      'Acco Pressboard Covers with Storage Hooks, 14 7/8" x 11", Executive Red',
    sales: 6.858,
    quantity: 6,
    discount: 0.7,
    profit: -5.715,
  },
  {
    rowId: 34,
    orderId: "US-2015-150630",
    orderDate: "9/17/15",
    shipDate: "9/21/15",
    shipMode: "Standard Class",
    customerId: "TB-21520",
    customerName: "Tracy Blumstein",
    segment: "Consumer",
    country: "United States",
    city: "Philadelphia",
    state: "Pennsylvania",
    postalCode: 19140,
    region: "East",
    productId: "OFF-AR-10001683",
    category: "Office Supplies",
    subCategory: "Art",
    productName: "Lumber Crayons",
    sales: 15.76,
    quantity: 2,
    discount: 0.2,
    profit: 3.546,
  },
  {
    rowId: 35,
    orderId: "CA-2017-107727",
    orderDate: "10/19/17",
    shipDate: "10/23/17",
    shipMode: "Second Class",
    customerId: "MA-17560",
    customerName: "Matt Abelman",
    segment: "Home Office",
    country: "United States",
    city: "Houston",
    state: "Texas",
    postalCode: 77095,
    region: "Central",
    productId: "OFF-PA-10000249",
    category: "Office Supplies",
    subCategory: "Paper",
    productName: "Easy-staple paper",
    sales: 29.472,
    quantity: 3,
    discount: 0.2,
    profit: 9.9468,
  },
  {
    rowId: 36,
    orderId: "CA-2016-117590",
    orderDate: "12/8/16",
    shipDate: "12/10/16",
    shipMode: "First Class",
    customerId: "GH-14485",
    customerName: "Gene Hale",
    segment: "Corporate",
    country: "United States",
    city: "Richardson",
    state: "Texas",
    postalCode: 75080,
    region: "Central",
    productId: "TEC-PH-10004977",
    category: "Technology",
    subCategory: "Phones",
    productName: "GE 30524EE4",
    sales: 1097.544,
    quantity: 7,
    discount: 0.2,
    profit: 123.4737,
  },
  {
    rowId: 37,
    orderId: "CA-2016-117590",
    orderDate: "12/8/16",
    shipDate: "12/10/16",
    shipMode: "First Class",
    customerId: "GH-14485",
    customerName: "Gene Hale",
    segment: "Corporate",
    country: "United States",
    city: "Richardson",
    state: "Texas",
    postalCode: 75080,
    region: "Central",
    productId: "FUR-FU-10003664",
    category: "Furniture",
    subCategory: "Furnishings",
    productName: "Electrix Architect's Clamp-On Swing Arm Lamp, Black",
    sales: 190.92,
    quantity: 5,
    discount: 0.6,
    profit: -147.963,
  },
  {
    rowId: 38,
    orderId: "CA-2015-117415",
    orderDate: "12/27/15",
    shipDate: "12/31/15",
    shipMode: "Standard Class",
    customerId: "SN-20710",
    customerName: "Steve Nguyen",
    segment: "Home Office",
    country: "United States",
    city: "Houston",
    state: "Texas",
    postalCode: 77041,
    region: "Central",
    productId: "OFF-EN-10002986",
    category: "Office Supplies",
    subCategory: "Envelopes",
    productName: '#10-4 1/8" x 9 1/2" Premium Diagonal Seam Envelopes',
    sales: 113.328,
    quantity: 9,
    discount: 0.2,
    profit: 35.415,
  },
  {
    rowId: 39,
    orderId: "CA-2015-117415",
    orderDate: "12/27/15",
    shipDate: "12/31/15",
    shipMode: "Standard Class",
    customerId: "SN-20710",
    customerName: "Steve Nguyen",
    segment: "Home Office",
    country: "United States",
    city: "Houston",
    state: "Texas",
    postalCode: 77041,
    region: "Central",
    productId: "FUR-BO-10002545",
    category: "Furniture",
    subCategory: "Bookcases",
    productName: "Atlantic Metals Mobile 3-Shelf Bookcases, Custom Colors",
    sales: 532.3992,
    quantity: 3,
    discount: 0.32,
    profit: -46.9764,
  },
  {
    rowId: 40,
    orderId: "CA-2015-117415",
    orderDate: "12/27/15",
    shipDate: "12/31/15",
    shipMode: "Standard Class",
    customerId: "SN-20710",
    customerName: "Steve Nguyen",
    segment: "Home Office",
    country: "United States",
    city: "Houston",
    state: "Texas",
    postalCode: 77041,
    region: "Central",
    productId: "FUR-CH-10004218",
    category: "Furniture",
    subCategory: "Chairs",
    productName: "Global Fabric Manager's Chair, Dark Gray",
    sales: 212.058,
    quantity: 3,
    discount: 0.3,
    profit: -15.147,
  },
  {
    rowId: 41,
    orderId: "CA-2015-117415",
    orderDate: "12/27/15",
    shipDate: "12/31/15",
    shipMode: "Standard Class",
    customerId: "SN-20710",
    customerName: "Steve Nguyen",
    segment: "Home Office",
    country: "United States",
    city: "Houston",
    state: "Texas",
    postalCode: 77041,
    region: "Central",
    productId: "TEC-PH-10000486",
    category: "Technology",
    subCategory: "Phones",
    productName: "Plantronics HL10 Handset Lifter",
    sales: 371.168,
    quantity: 4,
    discount: 0.2,
    profit: 41.7564,
  },
  {
    rowId: 42,
    orderId: "CA-2017-120999",
    orderDate: "9/10/17",
    shipDate: "9/15/17",
    shipMode: "Standard Class",
    customerId: "LC-16930",
    customerName: "Linda Cazamias",
    segment: "Corporate",
    country: "United States",
    city: "Naperville",
    state: "Illinois",
    postalCode: 60540,
    region: "Central",
    productId: "TEC-PH-10004093",
    category: "Technology",
    subCategory: "Phones",
    productName: "Panasonic Kx-TS550",
    sales: 147.168,
    quantity: 4,
    discount: 0.2,
    profit: 16.5564,
  },
  {
    rowId: 43,
    orderId: "CA-2016-101343",
    orderDate: "7/17/16",
    shipDate: "7/22/16",
    shipMode: "Standard Class",
    customerId: "RA-19885",
    customerName: "Ruben Ausman",
    segment: "Corporate",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90049,
    region: "West",
    productId: "OFF-ST-10003479",
    category: "Office Supplies",
    subCategory: "Storage",
    productName: "Eldon Base for stackable storage shelf, platinum",
    sales: 77.88,
    quantity: 2,
    discount: 0,
    profit: 3.894,
  },
  {
    rowId: 44,
    orderId: "CA-2017-139619",
    orderDate: "9/19/17",
    shipDate: "9/23/17",
    shipMode: "Standard Class",
    customerId: "ES-14080",
    customerName: "Erin Smith",
    segment: "Corporate",
    country: "United States",
    city: "Melbourne",
    state: "Florida",
    postalCode: 32935,
    region: "South",
    productId: "OFF-ST-10003282",
    category: "Office Supplies",
    subCategory: "Storage",
    productName:
      "Advantus 10-Drawer Portable Organizer, Chrome Metal Frame, Smoke Drawers",
    sales: 95.616,
    quantity: 2,
    discount: 0.2,
    profit: 9.5616,
  },
  {
    rowId: 45,
    orderId: "CA-2016-118255",
    orderDate: "3/11/16",
    shipDate: "3/13/16",
    shipMode: "First Class",
    customerId: "ON-18715",
    customerName: "Odella Nelson",
    segment: "Corporate",
    country: "United States",
    city: "Eagan",
    state: "Minnesota",
    postalCode: 55122,
    region: "Central",
    productId: "TEC-AC-10000171",
    category: "Technology",
    subCategory: "Accessories",
    productName:
      "Verbatim 25 GB 6x Blu-ray Single Layer Recordable Disc, 25/Pack",
    sales: 45.98,
    quantity: 2,
    discount: 0,
    profit: 19.7714,
  },
  {
    rowId: 46,
    orderId: "CA-2016-118255",
    orderDate: "3/11/16",
    shipDate: "3/13/16",
    shipMode: "First Class",
    customerId: "ON-18715",
    customerName: "Odella Nelson",
    segment: "Corporate",
    country: "United States",
    city: "Eagan",
    state: "Minnesota",
    postalCode: 55122,
    region: "Central",
    productId: "OFF-BI-10003291",
    category: "Office Supplies",
    subCategory: "Binders",
    productName: "Wilson Jones Leather-Like Binders with DublLock Round Rings",
    sales: 17.46,
    quantity: 2,
    discount: 0,
    profit: 8.2062,
  },
  {
    rowId: 47,
    orderId: "CA-2014-146703",
    orderDate: "10/20/14",
    shipDate: "10/25/14",
    shipMode: "Second Class",
    customerId: "PO-18865",
    customerName: "Patrick O'Donnell",
    segment: "Consumer",
    country: "United States",
    city: "Westland",
    state: "Michigan",
    postalCode: 48185,
    region: "Central",
    productId: "OFF-ST-10001713",
    category: "Office Supplies",
    subCategory: "Storage",
    productName:
      "Gould Plastics 9-Pocket Panel Bin, 18-3/8w x 5-1/4d x 20-1/2h, Black",
    sales: 211.96,
    quantity: 4,
    discount: 0,
    profit: 8.4784,
  },
  {
    rowId: 48,
    orderId: "CA-2016-169194",
    orderDate: "6/20/16",
    shipDate: "6/25/16",
    shipMode: "Standard Class",
    customerId: "LH-16900",
    customerName: "Lena Hernandez",
    segment: "Consumer",
    country: "United States",
    city: "Dover",
    state: "Delaware",
    postalCode: 19901,
    region: "East",
    productId: "TEC-AC-10002167",
    category: "Technology",
    subCategory: "Accessories",
    productName: "Imation 8gb Micro Traveldrive Usb 2.0 Flash Drive",
    sales: 45,
    quantity: 3,
    discount: 0,
    profit: 4.95,
  },
  {
    rowId: 49,
    orderId: "CA-2016-169194",
    orderDate: "6/20/16",
    shipDate: "6/25/16",
    shipMode: "Standard Class",
    customerId: "LH-16900",
    customerName: "Lena Hernandez",
    segment: "Consumer",
    country: "United States",
    city: "Dover",
    state: "Delaware",
    postalCode: 19901,
    region: "East",
    productId: "TEC-PH-10003988",
    category: "Technology",
    subCategory: "Phones",
    productName:
      "LF Elite 3D Dazzle Designer Hard Case Cover, Lf Stylus Pen and Wiper For Apple Iphone 5c Mini Lite",
    sales: 21.8,
    quantity: 2,
    discount: 0,
    profit: 6.104,
  },
  {
    rowId: 50,
    orderId: "CA-2015-115742",
    orderDate: "4/18/15",
    shipDate: "4/22/15",
    shipMode: "Standard Class",
    customerId: "DP-13000",
    customerName: "Darren Powers",
    segment: "Consumer",
    country: "United States",
    city: "New Albany",
    state: "Indiana",
    postalCode: 47150,
    region: "Central",
    productId: "OFF-BI-10004410",
    category: "Office Supplies",
    subCategory: "Binders",
    productName:
      "C-Line Peel & Stick Add-On Filing Pockets, 8-3/4 x 5-1/8, 10/Pack",
    sales: 38.22,
    quantity: 6,
    discount: 0,
    profit: 17.9634,
  },
  {
    rowId: 51,
    orderId: "CA-2015-115742",
    orderDate: "4/18/15",
    shipDate: "4/22/15",
    shipMode: "Standard Class",
    customerId: "DP-13000",
    customerName: "Darren Powers",
    segment: "Consumer",
    country: "United States",
    city: "New Albany",
    state: "Indiana",
    postalCode: 47150,
    region: "Central",
    productId: "OFF-LA-10002762",
    category: "Office Supplies",
    subCategory: "Labels",
    productName: "Avery 485",
    sales: 75.18,
    quantity: 6,
    discount: 0,
    profit: 35.3346,
  },
  {
    rowId: 52,
    orderId: "CA-2015-115742",
    orderDate: "4/18/15",
    shipDate: "4/22/15",
    shipMode: "Standard Class",
    customerId: "DP-13000",
    customerName: "Darren Powers",
    segment: "Consumer",
    country: "United States",
    city: "New Albany",
    state: "Indiana",
    postalCode: 47150,
    region: "Central",
    productId: "FUR-FU-10001706",
    category: "Furniture",
    subCategory: "Furnishings",
    productName: "Longer-Life Soft White Bulbs",
    sales: 6.16,
    quantity: 2,
    discount: 0,
    profit: 2.9568,
  },
  {
    rowId: 53,
    orderId: "CA-2015-115742",
    orderDate: "4/18/15",
    shipDate: "4/22/15",
    shipMode: "Standard Class",
    customerId: "DP-13000",
    customerName: "Darren Powers",
    segment: "Consumer",
    country: "United States",
    city: "New Albany",
    state: "Indiana",
    postalCode: 47150,
    region: "Central",
    productId: "FUR-CH-10003061",
    category: "Furniture",
    subCategory: "Chairs",
    productName: "Global Leather Task Chair, Black",
    sales: 89.99,
    quantity: 1,
    discount: 0,
    profit: 17.0981,
  },
  {
    rowId: 54,
    orderId: "CA-2016-105816",
    orderDate: "12/11/16",
    shipDate: "12/17/16",
    shipMode: "Standard Class",
    customerId: "JM-15265",
    customerName: "Janet Molinari",
    segment: "Corporate",
    country: "United States",
    city: "New York City",
    state: "New York",
    postalCode: 10024,
    region: "East",
    productId: "OFF-FA-10000304",
    category: "Office Supplies",
    subCategory: "Fasteners",
    productName: "Advantus Push Pins",
    sales: 15.26,
    quantity: 7,
    discount: 0,
    profit: 6.2566,
  },
  {
    rowId: 55,
    orderId: "CA-2016-105816",
    orderDate: "12/11/16",
    shipDate: "12/17/16",
    shipMode: "Standard Class",
    customerId: "JM-15265",
    customerName: "Janet Molinari",
    segment: "Corporate",
    country: "United States",
    city: "New York City",
    state: "New York",
    postalCode: 10024,
    region: "East",
    productId: "TEC-PH-10002447",
    category: "Technology",
    subCategory: "Phones",
    productName: "AT&T CL83451 4-Handset Telephone",
    sales: 1029.95,
    quantity: 5,
    discount: 0,
    profit: 298.6855,
  },
  {
    rowId: 56,
    orderId: "CA-2016-111682",
    orderDate: "6/17/16",
    shipDate: "6/18/16",
    shipMode: "First Class",
    customerId: "TB-21055",
    customerName: "Ted Butterfield",
    segment: "Consumer",
    country: "United States",
    city: "Troy",
    state: "New York",
    postalCode: 12180,
    region: "East",
    productId: "OFF-ST-10000604",
    category: "Office Supplies",
    subCategory: "Storage",
    productName: "Home/Office Personal File Carts",
    sales: 208.56,
    quantity: 6,
    discount: 0,
    profit: 52.14,
  },
  {
    rowId: 57,
    orderId: "CA-2016-111682",
    orderDate: "6/17/16",
    shipDate: "6/18/16",
    shipMode: "First Class",
    customerId: "TB-21055",
    customerName: "Ted Butterfield",
    segment: "Consumer",
    country: "United States",
    city: "Troy",
    state: "New York",
    postalCode: 12180,
    region: "East",
    productId: "OFF-PA-10001569",
    category: "Office Supplies",
    subCategory: "Paper",
    productName: "Xerox 232",
    sales: 32.4,
    quantity: 5,
    discount: 0,
    profit: 15.552,
  },
  {
    rowId: 58,
    orderId: "CA-2016-111682",
    orderDate: "6/17/16",
    shipDate: "6/18/16",
    shipMode: "First Class",
    customerId: "TB-21055",
    customerName: "Ted Butterfield",
    segment: "Consumer",
    country: "United States",
    city: "Troy",
    state: "New York",
    postalCode: 12180,
    region: "East",
    productId: "FUR-CH-10003968",
    category: "Furniture",
    subCategory: "Chairs",
    productName: "Novimex Turbo Task Chair",
    sales: 319.41,
    quantity: 5,
    discount: 0.1,
    profit: 7.098,
  },
  {
    rowId: 59,
    orderId: "CA-2016-111682",
    orderDate: "6/17/16",
    shipDate: "6/18/16",
    shipMode: "First Class",
    customerId: "TB-21055",
    customerName: "Ted Butterfield",
    segment: "Consumer",
    country: "United States",
    city: "Troy",
    state: "New York",
    postalCode: 12180,
    region: "East",
    productId: "OFF-PA-10000587",
    category: "Office Supplies",
    subCategory: "Paper",
    productName: "Array Parchment Paper, Assorted Colors",
    sales: 14.56,
    quantity: 2,
    discount: 0,
    profit: 6.9888,
  },
  {
    rowId: 60,
    orderId: "CA-2016-111682",
    orderDate: "6/17/16",
    shipDate: "6/18/16",
    shipMode: "First Class",
    customerId: "TB-21055",
    customerName: "Ted Butterfield",
    segment: "Consumer",
    country: "United States",
    city: "Troy",
    state: "New York",
    postalCode: 12180,
    region: "East",
    productId: "TEC-AC-10002167",
    category: "Technology",
    subCategory: "Accessories",
    productName: "Imation 8gb Micro Traveldrive Usb 2.0 Flash Drive",
    sales: 30,
    quantity: 2,
    discount: 0,
    profit: 3.3,
  },
  {
    rowId: 61,
    orderId: "CA-2016-111682",
    orderDate: "6/17/16",
    shipDate: "6/18/16",
    shipMode: "First Class",
    customerId: "TB-21055",
    customerName: "Ted Butterfield",
    segment: "Consumer",
    country: "United States",
    city: "Troy",
    state: "New York",
    postalCode: 12180,
    region: "East",
    productId: "OFF-BI-10001460",
    category: "Office Supplies",
    subCategory: "Binders",
    productName: "Plastic Binding Combs",
    sales: 48.48,
    quantity: 4,
    discount: 0.2,
    profit: 16.362,
  },
  {
    rowId: 62,
    orderId: "CA-2016-111682",
    orderDate: "6/17/16",
    shipDate: "6/18/16",
    shipMode: "First Class",
    customerId: "TB-21055",
    customerName: "Ted Butterfield",
    segment: "Consumer",
    country: "United States",
    city: "Troy",
    state: "New York",
    postalCode: 12180,
    region: "East",
    productId: "OFF-AR-10001868",
    category: "Office Supplies",
    subCategory: "Art",
    productName: "Prang Dustless Chalk Sticks",
    sales: 1.68,
    quantity: 1,
    discount: 0,
    profit: 0.84,
  },
  {
    rowId: 63,
    orderId: "CA-2015-135545",
    orderDate: "11/24/15",
    shipDate: "11/30/15",
    shipMode: "Standard Class",
    customerId: "KM-16720",
    customerName: "Kunst Miller",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90004,
    region: "West",
    productId: "TEC-AC-10004633",
    category: "Technology",
    subCategory: "Accessories",
    productName:
      "Verbatim 25 GB 6x Blu-ray Single Layer Recordable Disc, 3/Pack",
    sales: 13.98,
    quantity: 2,
    discount: 0,
    profit: 6.1512,
  },
  {
    rowId: 64,
    orderId: "CA-2015-135545",
    orderDate: "11/24/15",
    shipDate: "11/30/15",
    shipMode: "Standard Class",
    customerId: "KM-16720",
    customerName: "Kunst Miller",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90004,
    region: "West",
    productId: "OFF-BI-10001078",
    category: "Office Supplies",
    subCategory: "Binders",
    productName:
      'Acco PRESSTEX Data Binder with Storage Hooks, Dark Blue, 14 7/8" X 11"',
    sales: 25.824,
    quantity: 6,
    discount: 0.2,
    profit: 9.3612,
  },
  {
    rowId: 65,
    orderId: "CA-2015-135545",
    orderDate: "11/24/15",
    shipDate: "11/30/15",
    shipMode: "Standard Class",
    customerId: "KM-16720",
    customerName: "Kunst Miller",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90004,
    region: "West",
    productId: "OFF-PA-10003892",
    category: "Office Supplies",
    subCategory: "Paper",
    productName: "Xerox 1943",
    sales: 146.73,
    quantity: 3,
    discount: 0,
    profit: 68.9631,
  },
  {
    rowId: 66,
    orderId: "CA-2015-135545",
    orderDate: "11/24/15",
    shipDate: "11/30/15",
    shipMode: "Standard Class",
    customerId: "KM-16720",
    customerName: "Kunst Miller",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90004,
    region: "West",
    productId: "FUR-FU-10000397",
    category: "Furniture",
    subCategory: "Furnishings",
    productName: "Luxo Economy Swing Arm Lamp",
    sales: 79.76,
    quantity: 4,
    discount: 0,
    profit: 22.3328,
  },
  {
    rowId: 67,
    orderId: "US-2015-164175",
    orderDate: "4/30/15",
    shipDate: "5/5/15",
    shipMode: "Standard Class",
    customerId: "PS-18970",
    customerName: "Paul Stevenson",
    segment: "Home Office",
    country: "United States",
    city: "Chicago",
    state: "Illinois",
    postalCode: 60610,
    region: "Central",
    productId: "FUR-CH-10001146",
    category: "Furniture",
    subCategory: "Chairs",
    productName: "Global Value Mid-Back Manager's Chair, Gray",
    sales: 213.115,
    quantity: 5,
    discount: 0.3,
    profit: -15.2225,
  },
  {
    rowId: 68,
    orderId: "CA-2014-106376",
    orderDate: "12/5/14",
    shipDate: "12/10/14",
    shipMode: "Standard Class",
    customerId: "BS-11590",
    customerName: "Brendan Sweed",
    segment: "Corporate",
    country: "United States",
    city: "Gilbert",
    state: "Arizona",
    postalCode: 85234,
    region: "West",
    productId: "OFF-AR-10002671",
    category: "Office Supplies",
    subCategory: "Art",
    productName:
      "Hunt BOSTON Model 1606 High-Volume Electric Pencil Sharpener, Beige",
    sales: 1113.024,
    quantity: 8,
    discount: 0.2,
    profit: 111.3024,
  },
  {
    rowId: 3738,
    orderId: "CA-2016-115476",
    orderDate: "3/17/16",
    shipDate: "3/17/16",
    shipMode: "Same Day",
    customerId: "VM-21835",
    customerName: "Vivian Mathis",
    segment: "Consumer",
    country: "United States",
    city: "Newark",
    state: "Delaware",
    postalCode: 19711,
    region: "East",
    productId: "OFF-BI-10000962",
    category: "Office Supplies",
    subCategory: "Binders",
    productName:
      'Acco Flexible ACCOHIDE Square Ring Data Binder, Dark Blue, 11 1/2" X 14" 7/8"',
    sales: 32.54,
    quantity: 2,
    discount: 0,
    profit: 15.9446,
  },
  {
    rowId: 3739,
    orderId: "CA-2016-133340",
    orderDate: "12/9/16",
    shipDate: "12/13/16",
    shipMode: "Standard Class",
    customerId: "LH-17155",
    customerName: "Logan Haushalter",
    segment: "Consumer",
    country: "United States",
    city: "Jackson",
    state: "Michigan",
    postalCode: 49201,
    region: "Central",
    productId: "TEC-PH-10003988",
    category: "Technology",
    subCategory: "Phones",
    productName:
      "LF Elite 3D Dazzle Designer Hard Case Cover, Lf Stylus Pen and Wiper For Apple Iphone 5c Mini Lite",
    sales: 10.9,
    quantity: 1,
    discount: 0,
    profit: 3.052,
  },
];

module.exports = JSONData;
